version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: reprint-gcs
    main: ./cmd/reprint-gcs
    binary: reprint-gcs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: reprint-s3
    main: ./cmd/reprint-s3
    binary: reprint-s3
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Skip until implemented
    skip: true

archives:
  - id: reprint-gcs
    builds:
      - reprint-gcs
    name_template: "reprint-gcs_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: reprint-gcs
    ids:
      - reprint-gcs
    repository:
      owner: minodisk
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/minodisk/reprint
    description: External image uploader CLI for deck using Google Cloud Storage
    license: MIT
    install: |
      bin.install "reprint-gcs"
    test: |
      system "#{bin}/reprint-gcs", "--help"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
